### ISSUE TITLE
Documentation: Firecracker limitations

### ISSUE THREAD

**Issue by egernst** [kata-containers/documentation#351]
With its limited feature support, there are expected functional limitations when using Kata Containers with the Firecracker hypervisor.

This issue serves as a location to track these limitations.
- [ ] Volume Support and Host to Guest file sharing https://github.com/kata-containers/runtime/issues/1071
       Due to lack of host to guest file sharing support in Firecracker, volumes and more importantly Kubernetes secrets and config maps do not work. This means that some Kubernetes features do not current work with Firecracker.

- [ ] Resizing of CPU and Memory resource constraints
       Kata containers does not support resizing of Firecracker PODs.

Additionally as the support for Firecracker is preliminary, some features are yet to be implemented in the runtime. These include

- [ ] Unified configuration for Multi-hypervisors in kata-runtime kata-containers/runtime/issues/1082
      Kata containers today does not support choosing between multiple hypervisors using a single configuration.toml. There is a workaround possible today using a wrapper shell script to provide an alternate configuration file, which allows kata-runtime to support multiple hypervisors on the same node as shown here 
        https://github.com/clearlinux/cloud-native-setup/blob/master/clr-k8s-examples/setup_kata_firecracker.sh#L63
- [ ] Support for Jailer https://github.com/kata-containers/runtime/issues/1129
     Kata containers does not use jailer to constrain firecracker.
- [ ] Support for CPU and Memory resource constraints
     Kata containers does not apply the container CPU and Memory constraints for Firecracker PODs.

**Comment by mcastelino** [comment]
https://github.com/kata-containers/runtime/issues/1082

**Comment by mcastelino** [comment]
https://github.com/kata-containers/runtime/issues/1071

**Comment by mcastelino** [comment]
https://github.com/kata-containers/runtime/issues/1124

**Comment by grahamwhaley** [comment]
Just a note - when we do finally write the kata/fc docs into a markdown, can we also list the pre-requisites along with the limitations?
I've added a couple to the [wiki page](https://github.com/kata-containers/documentation/wiki/Initial-release-of-Kata-Containers-with-Firecracker-support) as a start:

- must have `vhost_vsock`
- must have block based storage backend

Please add more here, and to the wiki page, if you know of them.
